projects:
  default:
    schema:
      - ../reporter/api/graphql/schema/*.graphqls
      - ./$houdini/graphql/schema.graphql
    documents:
      - '**/*.gql'
      - '**/*.svelte'
      - ./$houdini/graphql/documents.gql
